### ISSUE TITLE
Datentypen

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#1]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/24cec907cc73cbbe9798dfd9a69f1306f1bf23e7/chapter_04_worksheet.py#L29

Es fehlt kein Datentyp. Da ist bereits ein Datentyp vorhanden. Welcher Datentyp ist das? Falls du es nicht weiß, google nach "Python Input"

**Comment by MarvinKhn** [comment]
standard datentyp ist ein string
changed:
x = input("Enter a number: ") #Der Input hat einen string als Datentyp, es muss ein int sein
