### ISSUE TITLE
Task 12 and 13 missing?

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#11]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/837bd05d73f398f7eff0f04a8902a04e172485ae/Python%20Chapter/Chapter%206/chapter_06_chaptertask.py#L98

are you still working on the task 12 and 13?
if not write a comment in your file that you didnt do them

**Comment by MarvinKhn** [comment]
added
