### ISSUE TITLE
Sample for Chapter 6 Lab Task 3

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#12]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/837bd05d73f398f7eff0f04a8902a04e172485ae/Python%20Chapter/Chapter%206/chapter_06_lab.py#L24

if you want to have a look for an example 
[Part 3](https://github.com/T-systemsYoungsters/phan-LOGIST/blob/cb502d5ea0e90b99d180e1c47cfa3fec6741dbaa/python/lab/lab_6.md)

otherwise you can close this issue

**Comment by MarvinKhn** [comment]
okay nice, maybe you can explain me the code and why it is only possible with 0-6, after your holiday

**Comment by phtrong** [comment]
sure we can. 
its only possible with 0-6 because the resulting numbers are single digits 
with 7 or more your will get double digits which will shift the numbers
just try with 7 or 8 and you will see it
