### ISSUE TITLE
Making your code complex

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#2]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/24cec907cc73cbbe9798dfd9a69f1306f1bf23e7/chapter_04_lab.py#L4

if your want to print blank lines please use print()

x = ''
print(x)
is confusing because I expected a variable everytime

**Comment by MarvinKhn** [comment]
changed to print()
