### ISSUE TITLE
Single Quotes and double Quotes

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#3]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/24cec907cc73cbbe9798dfd9a69f1306f1bf23e7/chapter_04_lab.py#L41

please use your quotes consistently 
if you are not sure which one to use when 
here is a link https://www.askpython.com/python/string/difference-between-single-and-double-quotes-in-python#:~:text=What%20are%20single%20quotes%20used,%E2%80%93%20'my%2Didentifier'.

**Comment by MarvinKhn** [comment]
changed to single quotes
