### ISSUE TITLE
requirements mistake

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#5]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/24cec907cc73cbbe9798dfd9a69f1306f1bf23e7/chapter_04_lab.py#L62

line 62 only gives you a number from 1-2 inclusive 
not fulfilling the task requirements 1-3 inclusive

**Comment by MarvinKhn** [comment]
camel_tiredness += random.randrange(1,4)

changed: 3 to 4
