### ISSUE TITLE
operator mistake

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#6]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/24cec907cc73cbbe9798dfd9a69f1306f1bf23e7/chapter_04_lab.py#L119

**Comment by MarvinKhn** [comment]
if miles_traveled >= 200 and natives_distance >= 0 and thirst <= 6 and camel_tiredness <= 8 :

added:  miles_traveled >= 200

**Comment by phtrong** [comment]
that was not the mistake i was talking about 
and you didnt change anything

**Comment by phtrong** [comment]
yes, but its important to know why. 
so before that you could still won even when the distant is 0 resulting in "catching you" 

natives_distance > 0 this should be the right answer

**Comment by MarvinKhn** [comment]
yeah, I understand
now I fixed ist correctly

if miles_traveled >= 200 and natives_distance > 0 and thirst <= 6 and camel_tiredness <= 8 :

but miles_traveled > 200 is also a logic mistake
