### ISSUE TITLE
requirement mistake and logical mistake

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#7]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/24cec907cc73cbbe9798dfd9a69f1306f1bf23e7/chapter_04_lab.py#L124
```python
randrange(1,20)
```
doesnt give you a 1 in 20 chances 

also the oasis can be found even after the game

**Comment by MarvinKhn** [comment]
oasis_chance = random.randrange(20)  /(1,20) to (20)
    if oasis_chance == 7 and done == False :     /can't be found after game
        drinks_canteen = 7
        thirst = 0
        camel_tiredness = 0
        print("You have found an oasis! You are reseting")
        print()
