### ISSUE TITLE
complex code 

### ISSUE THREAD

**Issue by phtrong** [T-systemsYoungsters/marvin-LOGIST#9]
https://github.com/T-systemsYoungsters/marvin-LOGIST/blob/24cec907cc73cbbe9798dfd9a69f1306f1bf23e7/chapter_05_lab.py#L32

can you please explain this code line?

**Comment by MarvinKhn** [comment]
Darstellung des Chassis?

**Comment by phtrong** [comment]
what does:

- pygame.draw.rect 
- screen 
- red
- pygame.Rect
- (190, 250, 125,30)

do?

**Comment by MarvinKhn** [comment]
hab nochmal im chapter geschaut, habe es jetzt angepasst
weiß leider nicht mehr von welcher seite das war

pygame.draw.rect(screen, RED, [190, 250, 125, 30])

**Comment by phtrong** [comment]
okay, will close the issue 
if you still want to know what pygame.Rect is doing, we can talk about it the upcoming days
